#include <stdio.h>
#include <string.h>
#include "ir.h"

void emit_python(IRInstr *ir) {
    FILE *f = fopen("output.py", "w");
    fprintf(f, "# Generated by MiniLang compiler\n\n");

    for (IRInstr *i = ir; i; i = i->next) {
        if      (!strcmp(i->op,"ASSIGN")) fprintf(f, "%s = %s\n",           i->dest, i->src1);
        else if (!strcmp(i->op,"ADD"))    fprintf(f, "%s = %s + %s\n",      i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"SUB"))    fprintf(f, "%s = %s - %s\n",      i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"MUL"))    fprintf(f, "%s = %s * %s\n",      i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"DIV"))    fprintf(f, "%s = %s / %s\n",      i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"GT"))     fprintf(f, "%s = %s > %s\n",      i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"LT"))     fprintf(f, "%s = %s < %s\n",      i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"GTE"))    fprintf(f, "%s = %s >= %s\n",     i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"LTE"))    fprintf(f, "%s = %s <= %s\n",     i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"EQ"))     fprintf(f, "%s = %s == %s\n",     i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"NEQ"))    fprintf(f, "%s = %s != %s\n",     i->dest, i->src1, i->src2);
        else if (!strcmp(i->op,"JUMPF"))  fprintf(f, "if not %s: pass  # goto %s\n", i->src1, i->dest);
        else if (!strcmp(i->op,"JUMP"))   fprintf(f, "# goto %s\n",         i->dest);
        else if (!strcmp(i->op,"LABEL"))  fprintf(f, "# label: %s\n",       i->dest);
    }

    fclose(f);
    printf("Python output written to output.py\n");
}
