#include <stdio.h>
#include <string.h>
#include "ir.h"

static void py_emit_str_or_none(FILE *f, const char *s) {
    if (!s) {
        fprintf(f, "None");
        return;
    }
    /* MiniLang identifiers/labels/ops are simple; emit as a Python single-quoted string. */
    fprintf(f, "'%s'", s);
}

void emit_python(IRInstr *ir) {
    FILE *f = fopen("output.py", "w");
    fprintf(f, "# Generated by MiniLang compiler\n\n");

    /* Emit IR as data and execute with a small interpreter so control flow works. */
    fprintf(f, "ir = [\n");
    for (IRInstr *i = ir; i; i = i->next) {
        fprintf(f, "    (");
        py_emit_str_or_none(f, i->op);
        fprintf(f, ", ");
        py_emit_str_or_none(f, i->dest);
        fprintf(f, ", ");
        py_emit_str_or_none(f, i->src1);
        fprintf(f, ", ");
        py_emit_str_or_none(f, i->src2);
        fprintf(f, "),\n");
    }
    fprintf(f, "]\n\n");

    fprintf(f, "label_to_pc = {}\n");
    fprintf(f, "for idx, (op, dest, src1, src2) in enumerate(ir):\n");
    fprintf(f, "    if op == 'LABEL':\n");
    fprintf(f, "        label_to_pc[dest] = idx\n\n");

    fprintf(f, "vars = {}\n\n");
    fprintf(f, "def val(x):\n");
    fprintf(f, "    if x is None:\n");
    fprintf(f, "        return None\n");
    fprintf(f, "    if isinstance(x, int):\n");
    fprintf(f, "        return x\n");
    fprintf(f, "    if isinstance(x, str) and (x.isdigit() or (x.startswith('-') and x[1:].isdigit())):\n");
    fprintf(f, "        return int(x)\n");
    fprintf(f, "    if x not in vars:\n");
    fprintf(f, "        raise NameError(f\"Undefined variable: {x}\")\n");
    fprintf(f, "    return vars[x]\n\n");

    fprintf(f, "pc = 0\n");
    fprintf(f, "while pc < len(ir):\n");
    fprintf(f, "    op, dest, src1, src2 = ir[pc]\n");
    fprintf(f, "    if op == 'ASSIGN':\n");
    fprintf(f, "        vars[dest] = val(src1)\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'ADD':\n");
    fprintf(f, "        vars[dest] = val(src1) + val(src2)\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'SUB':\n");
    fprintf(f, "        vars[dest] = val(src1) - val(src2)\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'MUL':\n");
    fprintf(f, "        vars[dest] = val(src1) * val(src2)\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'DIV':\n");
    fprintf(f, "        vars[dest] = val(src1) // val(src2)\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'GT':\n");
    fprintf(f, "        vars[dest] = 1 if (val(src1) > val(src2)) else 0\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'LT':\n");
    fprintf(f, "        vars[dest] = 1 if (val(src1) < val(src2)) else 0\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'GTE':\n");
    fprintf(f, "        vars[dest] = 1 if (val(src1) >= val(src2)) else 0\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'LTE':\n");
    fprintf(f, "        vars[dest] = 1 if (val(src1) <= val(src2)) else 0\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'EQ':\n");
    fprintf(f, "        vars[dest] = 1 if (val(src1) == val(src2)) else 0\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'NEQ':\n");
    fprintf(f, "        vars[dest] = 1 if (val(src1) != val(src2)) else 0\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'JUMPF':\n");
    fprintf(f, "        if val(src1) == 0:\n");
    fprintf(f, "            pc = label_to_pc[dest]\n");
    fprintf(f, "        else:\n");
    fprintf(f, "            pc += 1\n");
    fprintf(f, "    elif op == 'JUMP':\n");
    fprintf(f, "        pc = label_to_pc[dest]\n");
    fprintf(f, "    elif op == 'LABEL':\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    elif op == 'PRINT':\n");
    fprintf(f, "        print(val(src1))\n");
    fprintf(f, "        pc += 1\n");
    fprintf(f, "    else:\n");
    fprintf(f, "        raise ValueError(f\"Unknown IR op: {op}\")\n");

    fclose(f);
    printf("Python output written to output.py\n");
}
