# Generated by MiniLang compiler

ir = [
    ('ASSIGN', 'total', '0', None),
    ('ASSIGN', 'i', '1', None),
    ('LABEL', 'L0', None, None),
    ('LTE', 't0', 'i', '10'),
    ('JUMPF', 'L1', 't0', None),
    ('GT', 't1', 'i', '5'),
    ('JUMPF', 'L2', 't1', None),
    ('ADD', 't2', 'total', 'i'),
    ('ASSIGN', 'total', 't2', None),
    ('JUMP', 'L3', None, None),
    ('LABEL', 'L2', None, None),
    ('ASSIGN', 'total', 'total', None),
    ('LABEL', 'L3', None, None),
    ('ADD', 't4', 'i', '1'),
    ('ASSIGN', 'i', 't4', None),
    ('JUMP', 'L0', None, None),
    ('LABEL', 'L1', None, None),
    ('PRINT', None, 'total', None),
]

label_to_pc = {}
for idx, (op, dest, src1, src2) in enumerate(ir):
    if op == 'LABEL':
        label_to_pc[dest] = idx

vars = {}

def val(x):
    if x is None:
        return None
    if isinstance(x, int):
        return x
    if isinstance(x, str) and (x.isdigit() or (x.startswith('-') and x[1:].isdigit())):
        return int(x)
    if x not in vars:
        raise NameError(f"Undefined variable: {x}")
    return vars[x]

pc = 0
while pc < len(ir):
    op, dest, src1, src2 = ir[pc]
    if op == 'ASSIGN':
        vars[dest] = val(src1)
        pc += 1
    elif op == 'ADD':
        vars[dest] = val(src1) + val(src2)
        pc += 1
    elif op == 'SUB':
        vars[dest] = val(src1) - val(src2)
        pc += 1
    elif op == 'MUL':
        vars[dest] = val(src1) * val(src2)
        pc += 1
    elif op == 'DIV':
        vars[dest] = val(src1) // val(src2)
        pc += 1
    elif op == 'GT':
        vars[dest] = 1 if (val(src1) > val(src2)) else 0
        pc += 1
    elif op == 'LT':
        vars[dest] = 1 if (val(src1) < val(src2)) else 0
        pc += 1
    elif op == 'GTE':
        vars[dest] = 1 if (val(src1) >= val(src2)) else 0
        pc += 1
    elif op == 'LTE':
        vars[dest] = 1 if (val(src1) <= val(src2)) else 0
        pc += 1
    elif op == 'EQ':
        vars[dest] = 1 if (val(src1) == val(src2)) else 0
        pc += 1
    elif op == 'NEQ':
        vars[dest] = 1 if (val(src1) != val(src2)) else 0
        pc += 1
    elif op == 'JUMPF':
        if val(src1) == 0:
            pc = label_to_pc[dest]
        else:
            pc += 1
    elif op == 'JUMP':
        pc = label_to_pc[dest]
    elif op == 'LABEL':
        pc += 1
    elif op == 'PRINT':
        print(val(src1))
        pc += 1
    else:
        raise ValueError(f"Unknown IR op: {op}")
